### ISSUE TITLE
Unable to run CI locally

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight_range_limit#174]
Following instructions from README, `bundle exec rake ci` should " seed and
start a demo jetty server, build a clean test app, and run tests."

When I try it, it ends like the following. As a first step, curious if anyone else can reproduce. 

```
rake aborted!
LoadError: cannot load such file -- solr_wrapper/rake_task
/Users/jrochkind/.gem/ruby/2.6.6/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
/Users/jrochkind/.gem/ruby/2.6.6/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
/Users/jrochkind/.gem/ruby/2.6.6/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
/Users/jrochkind/.gem/ruby/2.6.6/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/Users/jrochkind/.gem/ruby/2.6.6/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
/Users/jrochkind/code/blacklight_range_limit/.internal_test_app/Rakefile:8:in `<top (required)>'
/Users/jrochkind/.gem/ruby/2.6.6/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-2.2.23/lib/bundler/cli/exec.rb:63:in `load'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-2.2.23/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-2.2.23/lib/bundler/cli/exec.rb:28:in `run'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-2.2.23/lib/bundler/cli.rb:474:in `exec'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-2.2.23/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-2.2.23/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-2.2.23/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-2.2.23/lib/bundler/cli.rb:30:in `dispatch'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-2.2.23/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-2.2.23/lib/bundler/cli.rb:24:in `start'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-2.2.23/exe/bundle:49:in `block in <top (required)>'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-2.2.23/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-2.2.23/exe/bundle:37:in `<top (required)>'
/Users/jrochkind/.gem/ruby/2.6.6/bin/bundle:23:in `load'
/Users/jrochkind/.gem/ruby/2.6.6/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
rake aborted!
EngineCart failed on with: pid 42999 exit 1
/Users/jrochkind/.gem/ruby/2.6.6/gems/engine_cart-2.3.0/lib/engine_cart/tasks/engine_cart.rake:128:in `block (3 levels) in <top (required)>'
/Users/jrochkind/.gem/ruby/2.6.6/gems/engine_cart-2.3.0/lib/engine_cart/tasks/engine_cart.rake:159:in `block (2 levels) in within_test_app'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler.rb:313:in `block in with_clean_env'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler.rb:562:in `with_env'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler.rb:313:in `with_clean_env'
/Users/jrochkind/.gem/ruby/2.6.6/gems/engine_cart-2.3.0/lib/engine_cart/tasks/engine_cart.rake:158:in `block in within_test_app'
/Users/jrochkind/.gem/ruby/2.6.6/gems/engine_cart-2.3.0/lib/engine_cart/tasks/engine_cart.rake:157:in `chdir'
/Users/jrochkind/.gem/ruby/2.6.6/gems/engine_cart-2.3.0/lib/engine_cart/tasks/engine_cart.rake:157:in `within_test_app'
/Users/jrochkind/.gem/ruby/2.6.6/gems/engine_cart-2.3.0/lib/engine_cart/tasks/engine_cart.rake:124:in `block (2 levels) in <top (required)>'
/Users/jrochkind/.gem/ruby/2.6.6/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/jrochkind/.gem/ruby/2.6.6/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/Users/jrochkind/.gem/ruby/2.6.6/bin/bundle:23:in `load'
/Users/jrochkind/.gem/ruby/2.6.6/bin/bundle:23:in `<main>'
Tasks: TOP => ci => engine_cart:generate
(See full trace by running task with --trace)
```

**Comment by jrochkind** [comment]
I can again!
