### ISSUE TITLE
Tests don't pass for me on master -- are they supposed to?

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight_range_limit#31]
master at 1523eccbc
~~~
Failures:

  1) Blacklight Range Limit should show the range limit facet
     Failure/Error: expect(page).to have_selector 'input.range_begin'
       expected to find css "input.range_begin" but there were no matches
     # ./spec/features/blacklight_range_limit_spec.rb:7:in `block (2 levels) in <top (required)>'

  2) Blacklight Range Limit should provide distribution information
     Failure/Error: click_link 'View distribution'
     Capybara::ElementNotFound:
       Unable to find link "View distribution"
     # /Users/jrochkind/.gem/ruby/1.9.3/gems/capybara-2.4.4/lib/capybara/node/finders.rb:41:in `block in find'
     # /Users/jrochkind/.gem/ruby/1.9.3/gems/capybara-2.4.4/lib/capybara/node/base.rb:84:in `synchronize'
     # /Users/jrochkind/.gem/ruby/1.9.3/gems/capybara-2.4.4/lib/capybara/node/finders.rb:30:in `find'
     # /Users/jrochkind/.gem/ruby/1.9.3/gems/capybara-2.4.4/lib/capybara/node/actions.rb:27:in `click_link'
     # /Users/jrochkind/.gem/ruby/1.9.3/gems/capybara-2.4.4/lib/capybara/session.rb:676:in `block (2 levels) in <class:Session>'
     # /Users/jrochkind/.gem/ruby/1.9.3/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/blacklight_range_limit_spec.rb:16:in `block (2 levels) in <top (required)>'

  3) Blacklight Range Limit should limit appropriately
     Failure/Error: click_link 'View distribution'
     Capybara::ElementNotFound:
       Unable to find link "View distribution"
     # /Users/jrochkind/.gem/ruby/1.9.3/gems/capybara-2.4.4/lib/capybara/node/finders.rb:41:in `block in find'
     # /Users/jrochkind/.gem/ruby/1.9.3/gems/capybara-2.4.4/lib/capybara/node/base.rb:84:in `synchronize'
     # /Users/jrochkind/.gem/ruby/1.9.3/gems/capybara-2.4.4/lib/capybara/node/finders.rb:30:in `find'
     # /Users/jrochkind/.gem/ruby/1.9.3/gems/capybara-2.4.4/lib/capybara/node/actions.rb:27:in `click_link'
     # /Users/jrochkind/.gem/ruby/1.9.3/gems/capybara-2.4.4/lib/capybara/session.rb:676:in `block (2 levels) in <class:Session>'
     # /Users/jrochkind/.gem/ruby/1.9.3/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/blacklight_range_limit_spec.rb:24:in `block (2 levels) in <top (required)>'

  4) Blacklight Range Limit with configured input labels should show the range limit facet
     Failure/Error: expect(page).to have_selector 'label.sr-only[for="range_pub_date_sort_begin"]', :text => 'from publication date'
       expected to find css "label.sr-only[for=\"range_pub_date_sort_begin\"]" with text "from publication date" but there were no matches
     # ./spec/features/blacklight_range_limit_spec.rb:45:in `block (2 levels) in <top (required)>'

Finished in 8.65 seconds (files took 3.33 seconds to load)
5 examples, 4 failures

Failed examples:

rspec ./spec/features/blacklight_range_limit_spec.rb:5 # Blacklight Range Limit should show the range limit facet
rspec ./spec/features/blacklight_range_limit_spec.rb:14 # Blacklight Range Limit should provide distribution information
rspec ./spec/features/blacklight_range_limit_spec.rb:22 # Blacklight Range Limit should limit appropriately
rspec ./spec/features/blacklight_range_limit_spec.rb:43 # Blacklight Range Limit with configured input labels should show the range limit facet
~~~

**Comment by jrochkind** [comment]
Looks like the failures happen running against tag v5.0.3 too.  So it may be failures started happening with a new version of BL (since tests always test against latest that gemspec allows), rather than any changes here. 

Hmm, still not sure how to proceed.  

I want to do a release that has the fix for ruby 2.2, 0080880b2

Not sure if I should do it off master, or backport that one fix so my release is just current 5.0.3 plus that, or what. 

I _think_ master is okay? Even though tests will pass in neither?

**Comment by cbeer** [comment]
That's 1.9.3 only, right? IIRC, (and @jcoyne would know better), there's something up with Rails 4.2 and Ruby 1.9..

**Comment by jrochkind** [comment]
Ah, maybe, let me run again with ruby 2.2.  Wow, running tests sure takes a while, with like 3-4 different bundle installs it looks like? 

Hmm, I can't get `bundle install` to work, even after deleting Gemfile.lock. I might have to run an engine_cart:clean or something, but I can't run any rake tasks, because bundler can't install, so. 

Not really sure what to do at this point, but I trust you that it's only 1.9.3?

Do you think I'm safe to release a blacklight_range_limit 5.0.4 off of master? I want the ruby 2.2.x fix. 

https://github.com/projectblacklight/blacklight_range_limit/compare/v5.0.3...master

**Comment by jrochkind** [comment]
`bundle install` on master does this for me:

~~~
Bundler could not find compatible versions for gem "rspec-mocks":
  In Gemfile:
    rspec-rails (~> 2.13) ruby depends on
      rspec-mocks (~> 2.13.0) ruby

    rspec (~> 3.0) ruby depends on
      rspec-mocks (3.0.0)
~~~

**Comment by jrochkind** [comment]
Okay, on a fresh checkout, tests pass in ruby 2.2.1, yep.  Not sure how to get `bundle install` to work on my previous checkout, engine_cart issues I guess, I'll just blow that away and start clean I guess.

**Comment by atz** [comment]
Closable?
